# Generated by Django 4.2.6 on 2023-11-15 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('experience_required', models.IntegerField()),
                ('skills_required', models.CharField(max_length=255)),
                ('starting_salary', models.IntegerField()),
                ('ending_salary', models.IntegerField()),
                ('languages', models.CharField(max_length=255)),
                ('resume', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb_app.jobs')),
            ],
        ),
    ]
