# Generated by Django 4.2.6 on 2023-11-16 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cb_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='resume',
        ),
    ]
