# Generated by Django 4.2.6 on 2023-11-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_app', '0003_usersprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='phone1_verfied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='phone2_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
